name: xn-g07
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - tqdm
  - scipy
  - pillow
  - numpy
  - pip:
      - wandb
      - nvitop
      # PyTorch amb CUDA 12.6 (recomanat per les VM del DCC)
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision
